name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: doxygen-install
      uses: ssciwr/doxygen-install@v1.6.0
      with:
        version: "1.12.0"

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    # Run de QA for code
    - name: Run static check
      run: composer run-script phpstan
    - name: Run mess detector
      run: composer run-script phpmd
    - name: Run Code Standard
      run: composer run-script phpcs
      
    # Generate docs
    - name: Generate docs
      run: composer run-script doxygen
      
